config/routes.rb
Rails.application.routes.draw do
  get 'connections/index'

  get 'connections/new'

  get 'connections/create'

  get 'connections/show'

  get 'connections/destroy'

  root 'welcome#index'

  get 'send_sms'  => 'verifications#create'
  get 'verify'    => 'verifications#confirm_code'
  patch 'verify'  => 'verifications#confirm_accepted'

  get 'broadcast' => 'verifications#confirm_broadcast'

  resources :accounts

  get 'set_session' => 'accounts#set_session'
  get 'login'   => 'accounts#new'
  get 'logout'  => 'accounts#logout'

  resources :providers
  get 'providers_login'            => 'providers#login_form'
  get 'providers_authenticate'   => 'providers#authenticate'
  get 'providers_revoke'           => 'providers#revoke'

  mount Authparty::API => '/api'
end

app/models/provider.rb
class Provider < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
            length: { minimum: 4, maximum: 35 }
  validates :api_key, presence: true, uniqueness: true
  has_many :tokens
end

app/controllers/providers_controller.rb
require 'securerandom'
require 'json'
class ProvidersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit]
  def index
    if current_user == nil
      redirect_to root_url, :flash => { :errors => 'You must be logged in
        to view this resource' }
    end
    if current_user.public_key == ENV['PUBLIC_KEY']
      @title = "Providers"
      @providers = Provider.all
    else
      redirect_to account_path(current_user), :flash => { :errors => 'You are not a admin.' }
    end
  end

  def new
    @title = "Create Provider"
    @provider = Provider.new
  end

  def create
    @provider = Provider.new(provider_params)
    @provider.api_key = SecureRandom.hex(15)
    @provider.api_secret = SecureRandom.hex(30)
    if @provider.save
      redirect_to provider_url(@provider)
    else
      redirect_to new_provider_url, :flash => { :errors => @provider.errors }
    end
  end

  def show
    @title = "Provider Information"
    @provider = Provider.find(params[:id])
    @authorizations = Connection.where(provider_id: @provider.id).all
    @tokens = @provider.tokens.all
    if @authorizations.count > 0
      @auth_count = 0
      @authorizations.each do |a|
        @auth_count = @auth_count + 1
      end
      @auth_msg = 'Authorization found: ' + @auth_count.to_s
    else
      @auth_msg = 'No authorizations found'
    end
  end

  def update
  end

  def login_form
    @provider = Provider.find_by(api_key: params[:api_key])
    if logged_in == true && @provider != nil
      @account = Account.find(current_user)
      if params[:token] != nil
        if @account.is_broadcasted == false
          redirect_to root_url, :flash => { :errors =>
            'You must first broadcast to confirm address ownership' }
        end
      else
        @title = 'Authorize ' + @provider.name
        render :layout => false
      end
    else
      redirect_to new_account_url + '?redirect=' + @provider.api_key
    end
  end

  def authenticate
    @account = Account.find(current_user)
    provider = Provider.find_by(api_key: params[:api_key])
    provider_exists = false
    @account.connections.each do |c|
      if c.provider_id = provider.id
        provider_exists = true
      end
    end
    if provider_exists == false
      connection = @account.connections.new
      connection.provider_id = provider.id
      connection.connected_on = Time.now
      connection.bearer = SecureRandom.hex(32)
      provider.number_connected += 1
      provider.save
      connection.save
    end
    redirect_to provider.callback_url + '?success=true&address=' + @account.public_key
  end

  def revoke
    @account = Account.find(params[:account])
    @account.connections.find_by(provider_id: params[:provider].to_i).destroy
    @account.save
    redirect_to account_path(@account), :flash => { :success => "Integration removed from account." }
  end

  private
  def provider_params
    params.require(:provider).permit(:name, :callback_url, :contact_email, :logo)
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/authenticate.html.erb
<h1>Providers#authenticate</h1>
<p>Find me in app/views/providers/authenticate.html.erb</p>

app/views/providers/create.html.erb
<h1>Providers#create</h1>
<p>Find me in app/views/providers/create.html.erb</p>

app/views/providers/index.html.erb
<div class="row" style="padding: 0px 25px 0px 25px;">
  <% @providers.each do |p| %>
    <div class="col-sm-12 col-md-6 col-lg-4 providers-div">
      <div class="well" style="margin-bottom: 0px;">
        <h3 class="pull-right"><%= link_to 'Details', provider_path(p.id), class: 'btn btn-primary' %></h3>
        <h3 class="pull-right"><a class="btn btn-info" style="margin-right: 10px;" role="button" data-toggle="collapse" href="#provider<%= p.id %>" aria-expanded="false" aria-controls="provider">Glance</a></h3>
        <h3><%= p.name %></h3>
        <hr />
        <div class="panel panel-default collapse" id="provider<%= p.id %>">
          <div class="panel-body">
            <p>
              <h5>Contact Email:</h5>
              <%= p.contact_email %>
              <hr />
            </p>
            <p>
              <h5>API Key:</h5>
              <%= p.api_key %>
              <hr />
            </p>
            <p>
              <h5>Callback URL:</h5>
              <%= p.callback_url %>
              <hr />
            </p>
            <p>
              <img class="pull-left logo" style="height: 50px; width: 50px; margin: 0px 15px 15px 0px;" src="<%= p.logo %>"/>
              <h5>Logo URL:</h5> <span style="word-wrap: break-word;"><%= p.logo %></span>
              <hr />
            </p>
            <p>
              <h5>Number Times Authorized:</h5>
              <%= p.number_connected %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/providers/login_form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %> | Authparty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body { padding: 20px 15px 20px 15px; }
    </style>
  </head>
  <body>
    <div class="container-fluid login_frame">
      <div class="row">
        <div class="col-sm-12">
          <%= image_tag(@provider.logo, class: "center-block img-thumbnail") %>
        </div>
        <div class="headline center-block" style="position: relative; top: 15px;">
          <h2><%= @provider.name %></h2>
          <h3>Is requesting to authorize you using your Authparty account. Would you like
           to authorize this action?</h3>
        </div>
      </div>
      <div class="row" style="margin-top: 35px;">
        <div class="col-sm-8 col-sm-offset-2 well well-lg">
          <%= link_to 'Confirm', providers_authenticate_path + '?api_key=' + @provider.api_key,
            :class => 'btn btn-lg btn-primary center-block' %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/providers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4 col-md-offset-3 col-lg-offset-4 well">
      <%= form_for :provider, url: providers_path do |f| %>
        <% if @provider.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@provider.errors.count, "error") %> prohibited
              this provider from being saved:
            </h2>
            <ul>
              <% @provider.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <p>
          <%= f.label :name %><br>
          <%= f.text_field :name, :class => 'form-control' %>
        </p>

        <p>
          <%= f.label :callback_url %><br>
          <%= f.text_field :callback_url, :class => 'form-control' %>
        </p>

        <p>
          <%= f.label :contact_email %><br>
          <%= f.email_field :contact_email, :class => 'form-control' %>
        </p>

        <p>
          <%= f.label :logo %><br>
          <%= f.text_field :logo, :class => 'form-control' %>
        </p>

        <p>
          <%= f.submit 'Create Provider', :class => 'btn btn-primary center-block' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/providers/show.html.erb
<div class="row margin-top">
  <div class="col-sm-12 col-md-4 col-lg-3" id="sidebar">
    <img class="img-responsive img-thumbnail logo center-block" src="<%= @provider.logo %>"></img>
    <hr />
    <ul class="nav menu" role="tablist">
      <li role="presentation" class="active"><a href="#overview" aria-controls="overview" role="tab" data-toggle="tab">Overview</a></li>
      <li role="presentation"><a href="#authorizations" aria-controls="authorizations" role="tab" data-toggle="tab">Authorizations</a></li>
      <li role="presentation"><a href="#tokens" aria-controls="tokens" role="tab" data-toggle="tab">Tokens</a></li>
      <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
    </ul>
  </div>
  <div class="col-sm-12 col-md-8 col-lg-9">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="overview">
        <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-8">
            <h1><%= @provider.name %> <small>Overview</small></h1>
            <p>A quick overview of your integration</p>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="item col-sm-12 col-md-4 col-lg-3">
            <h3>API Key
            <br />
            <small class="break"><%= @provider.api_key %></small></h3>
          </div>
          <div class="item col-sm-12 col-md-4 col-lg-3">
            <h3>API Secret
            <br />
            <small class="break"><%= @provider.api_secret %></small></h3>
          </div>
          <div class="item col-sm-12 col-md-4 col-lg-3">
            <h3>Connections
            <br />
            <small class="break"><%= @provider.number_connected %></small></h3>
          </div>
          <div class="item col-sm-12 col-md-4 col-lg-3">
            <h3>Tokens
            <br />
            <small class="break"><%= @provider.tokens.count %></small></h3>
          </div>
          <div class="item col-sm-12 col-md-4 col-lg-3">
            <h3>Created
            <br />
            <small class="break"><%= @provider.created_at %></small></h3>
          </div>
          <div class="item col-sm-12 col-md-4 col-lg-3">
            <h3>Updated
            <br />
            <small class="break"><%= @provider.updated_at %></small></h3>
          </div>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="authorizations">
        <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-8">
            <h1><%= @provider.name %> <small>Authorizations</small></h1>
            <p><%= @auth_msg %></p>
          </div>
          <% if @auth_count != 0 %>
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-striped"style="margin: 0px 10px 0px 10px;">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Connected</th>
                      <th>Bearer</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @authorizations.each do |a| %>
                      <tr>
                        <th scope="row"><%= a.id %></th>
                        <td><%= a.connected_on %></td>
                        <td><%= a.bearer %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="tokens">
        <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-8">
            <h1><%= @provider.name %> <small>Tokens</small></h1>
          </div>
        </div>
        <div class="row">
          <% if @provider.tokens.count != 0 %>
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-striped"style="margin: 0px 10px 0px 10px;">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Holders</th>
                      <th>Supply</th>
                      <th>Locked?</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @i = 0 %>
                    <% @provider.tokens.each do |t| %>
                      <tr>
                        <th scope="row"><%= t.id %></th>
                        <td><%= t.name %></td>
                        <td><%= link_to t.description, t.description %></td>
                        <td><%= t.holders %></td>
                        <td><%= t.supply %></td>
                        <td><%= t.locked %></td>
                      </tr>
                      <% @i = @i + 1 %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="settings">
        <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-8">
            <h1><%= @provider.name %> <small>Settings</small></h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>