config/routes.rb
Rails.application.routes.draw do
  get 'connections/index'

  get 'connections/new'

  get 'connections/create'

  get 'connections/show'

  get 'connections/destroy'

  root 'welcome#index'

  get 'send_sms'  => 'verifications#create'
  get 'verify'    => 'verifications#confirm_code'
  patch 'verify'  => 'verifications#confirm_accepted'

  get 'broadcast' => 'verifications#confirm_broadcast'

  resources :accounts

  get 'set_session' => 'accounts#set_session'
  get 'login'   => 'accounts#new'
  get 'logout'  => 'accounts#logout'

  resources :providers
  get 'providers_login'            => 'providers#login_form'
  get 'providers_authenticate'   => 'providers#authenticate'
  get 'providers_revoke'           => 'providers#revoke'

  mount Authparty::API => '/api'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @title = "Blockchain Authentication"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="jumbotron no-bottom-margin">
  <div class="container">
    <h1>Welcome to Authparty</h1>
    <p>Utilize your Counterparty-enabled wallet address to enable seameless,
     secure, and cross-service authentication.</p>
    <p>
      <% if logged_in == true %>
      <%= link_to 'My Authparty', account_path(current_user), :class => 'btn btn-primary btn-lg',
        :role => 'button' %></p>
      <% end %>
  </div>
</div>

<div class="row" style="margin-top: 25px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-md-offset-2 well">
        <h5>Mirror below button to trigger an authorization.</h5>
        <%= link_to 'Login with Authparty Example', providers_login_path + '?api_key=' + Provider.find(1).api_key,
          :onclick=>"window.open(this.href,'create_company', 'height=600, width=800');return false;" %>
        <pre style="margin-top: 15px;">&lt;a onclick="window.open(this.href,'create_company', 'height=475, width=800');return false;" href="https://authparty.herokuapp.com/providers_login?api_key=<%= Provider.find(1).api_key %>&amp;public_key=16gHsttasFz8T48MFsfzq199esvWTJGn94"&gt;Login with Authparty Example&lt;/a&gt;</pre>
        <h5 align="center">Token-based Providers Require Confirmed Broadcasts.</h5>
      </div>
    </div>
  </div>
</div>