config/routes.rb
Rails.application.routes.draw do
  get 'connections/index'

  get 'connections/new'

  get 'connections/create'

  get 'connections/show'

  get 'connections/destroy'

  root 'welcome#index'

  get 'send_sms'  => 'verifications#create'
  get 'verify'    => 'verifications#confirm_code'
  patch 'verify'  => 'verifications#confirm_accepted'

  get 'broadcast' => 'verifications#confirm_broadcast'

  resources :accounts

  get 'set_session' => 'accounts#set_session'
  get 'login'   => 'accounts#new'
  get 'logout'  => 'accounts#logout'

  resources :providers
  get 'providers_login'            => 'providers#login_form'
  get 'providers_authenticate'   => 'providers#authenticate'
  get 'providers_revoke'           => 'providers#revoke'

  mount Authparty::API => '/api'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %> | Authparty</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pusher.com/3.2/pusher.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default no-bottom-margin">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Authparty', root_url, :class => 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in == true %>
              <li><%= link_to 'Account', account_path(current_user) %></li>
              <% if current_user.public_key == ENV['PUBLIC_KEY'] %>
                <li><%= link_to 'Providers', providers_path %></li>
              <% end %>
              <li><%= link_to 'Logout', logout_path %></li>
            <% else %>
              <li><%= link_to 'Login', login_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if flash[:success] %>
      <div class="container alerts">
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Yay!</strong> <%= flash[:success] %>.
        </div>
      </div>
    <% end %>
    <% if flash[:errors] %>
      <div class="container alerts">
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Whoops! We have some issues</strong>.
          <ul>
            <li><%= flash[:errors] %></li>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login to Authparty">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Login to Authparty</h4>
          </div>
          <div class="modal-body">
            <%= form_for(:session, url: login_url, method: 'POST') do |f| %>
              <%= f.label :public_key %>
              <%= f.text_field :public_key, class: 'form-control' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.submit "Login", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <%= yield %>

    <% if Rails.env.production? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-58244508-4', 'auto');
      ga('send', 'pageview');
    </script>
    <% end %>
  </body>
</html>