config/routes.rb
Rails.application.routes.draw do
  get 'connections/index'

  get 'connections/new'

  get 'connections/create'

  get 'connections/show'

  get 'connections/destroy'

  root 'welcome#index'

  get 'send_sms'  => 'verifications#create'
  get 'verify'    => 'verifications#confirm_code'
  patch 'verify'  => 'verifications#confirm_accepted'

  get 'broadcast' => 'verifications#confirm_broadcast'

  resources :accounts

  get 'set_session' => 'accounts#set_session'
  get 'login'   => 'accounts#new'
  get 'logout'  => 'accounts#logout'

  resources :providers
  get 'providers_login'            => 'providers#login_form'
  get 'providers_authenticate'   => 'providers#authenticate'
  get 'providers_revoke'           => 'providers#revoke'

  mount Authparty::API => '/api'
end

app/models/account.rb
class Account < ApplicationRecord
  validates :public_key, allow_blank: true, uniqueness: true,
            length: { minimum: 26, maximum: 35 }
  has_many :connections

  def self.find_or_create_from_wallet_address(public_key)
    if account = Account.find_by(public_key: public_key)
      return account
    else
      Account.create(public_key: public_key)
    end
  end
end

app/controllers/accounts_controller.rb
require 'httparty'
require 'json'
require 'uri'
require "erb"
include ERB::Util
class AccountsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit]
  def index
    @title = "All Accounts"
    @account = Account.all
  end

  def new
    @account = Account.new
    @title = "Login"
    @generated_message = 'Authparty Login ' + generate_code(15)
    @generated_signature = 'Authparty Login ' + generate_code(15)
    @modal_id = generate_code(15)
    @provider = Provider.find_by(api_key: params[:redirect])
    if params[:redirect] != nil
      @callback = URI.escape(ENV['BASE_API_URL'] + '/api/v1/authorize_login?provider=' + params[:redirect] + '&modal_id=' + @modal_id)
      value = url_encode("?action=sign&message=" + URI.escape(@generated_message.to_s) + "&icon=" + url_encode(@provider.logo) + "&callback=" + url_encode(@callback))
      tapscan_value = "?action=sign&message=" + URI.escape(@generated_message.to_s) + "&icon=" + url_encode(@provider.logo) + "&callback=" + url_encode(@callback)
    else
      @callback = URI.escape(ENV['BASE_API_URL'] + '/api/v1/authorize_login?modal_id=' + @modal_id)
      value = url_encode("?action=sign&message=" + URI.escape(@generated_message.to_s) + "&icon=" + url_encode('http://authparty.io/Assets/authparty-icon-48x48.png') + "&callback=" + url_encode(@callback))
      tapscan_value = "?action=sign&message=" + URI.escape(@generated_message.to_s) + "&icon=" + url_encode('http://authparty.io/Assets/authparty-icon-48x48.png') + "&callback=" + url_encode(@callback)
    end
    @qr_data = value
    @tapscan = tapscan_value
  end

  def create
    if BitcoinCigs.verify_message(params[:account][:public_key],
      params[:account][:generated_signature], params[:account][:generated_message])
      @account = Account.find_or_create_from_wallet_address(params[:account][:public_key])
      if @account.broadcast_code == nil
        @account.broadcast_code = generate_code(15)
      end
      if @account.save
        if @account.persisted?
          notice = 'User was logged in.'
        else
          notice = 'User was created.'
        end
        session[:user] = @account.id
        session[:logged_in_at] = Time.now
        if params[:account][:redirect] != nil
          redirect_to providers_login_url + '?api_key=' + params[:account][:redirect]
        else
          redirect_to account_path(@account), :flash => { :success => notice }
        end
      else
        redirect_to new_account_url, :flash => { :errors => @account.errors }
      end
    else
      redirect_to new_account_url, :flash => { :errors => 'We could not confirm your authorization.' }
    end
  end

  def show
    @title = "Account"
    @account = Account.find(current_user)

    if @account.is_broadcasted == false
      @response = 'Valid broadcast not found on the blockchain.'
    else
      @response = 'Valid broadcast found and confirmed.'
    end

    @providers = []
    @account.connections.each do |c|
      @providers << Provider.find(c.provider_id)
    end

    # Check for Early Access Token (XAPEA)
    @early_access_token = false
    address_tokens = HTTParty.get('https://xchain.io/api/balances/' + @account.public_key)
    if address_tokens['error']
        @address_error = true
    else 
        address_tokens['data'].each do |t|
            if t['asset'] == 'XAPEA'
                @early_access_token = true
                @early_access_count = t['quantity']
            end
        end
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    @account.update(public_key: params[:account][:public_key])
    redirect_to account_path(@account), :flash => { :success => 'Account updated.' }
  end

  def set_session
    session[:logged_in_at] = Time.now
    session[:user] = params[:account]
  end

  def logout
    account = Account.find(session[:user])
    account.logged_out_at = Time.now
    account.save
    session.delete :user
    redirect_to root_url, :flash => { :success => 'User logged out.' }
  end

  def generate_code(number)
    charset = Array('A'..'Z') + Array('a'..'z')
    Array.new(number) { charset.sample }.join
  end

  protected
  def check_user
    @user = Account.find(session[:user])
    redirect_to root_path if @user = nil
  end

  private
  def account_params
    params.require(:account).permit(:public_key, :broadcast_code, :clef_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def current_user
    Account.find(session[:user])
  end

  def logged_in
    if session[:user] != nil
      account = Account.find(session[:user])
      if account.logged_out_at != nil
        if session[:logged_in_at] < account.logged_out_at
          return false
        else
          return true
        end
      else
        return true;
      end
    else
      return false;
    end
  end
end

app/views/accounts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4 col-md-offset-3 col-lg-offset-4">
      <%= form_for @account, method: 'patch' do |f| %>
      <% if @account.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@account.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @account.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :public_key %> (address)<br>
        <%= f.text_field :public_key %>
      </p>

      <p>
        <%= f.submit %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<h1>Listing Accounts</h1>

<table>
  <tr>
    <th>Public Key</th>
    <th>Mobile Number</th>
  </tr>

  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.public_key %></td>
      <td><%= account.mobile_number %></td>
      <td><%= link_to 'View', account_path(account) %></td>
    </tr>
  <% end %>
</table>

app/views/accounts/new.html.erb
<% if params[:redirect] != nil %>
  <!DOCTYPE html>
  <html>
    <head>
      <title><%= @title %> | Authparty</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <style>
        body { padding: 20px 15px 20px 15px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-4 col-md-offset-3 col-lg-offset-4">
            <h1 class="text-center" style="margin-bottom: 35px;">Wallet Login</h1>
            <%= form_for @account, url: accounts_path, method: 'POST' do |f| %>
              <% if @account.errors.any? %>
                <div id="error_explanation">
                  <h2>
                    <%= pluralize(@account.errors.count, "error") %> prohibited
                    this article from being saved:
                  </h2>
                  <ul>
                    <% @account.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <p>
                <div class="form-group">
                  <a href="<%= 'counterparty:' + @tapscan %>">
                    <img class="qr pull-left" src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=counterparty:<%= @qr_data %>" />
                  </a>
                  <h3>Message</h3>
                  <div class="input-group">
                    <%= f.text_field :generated_message, value: @generated_message,
                      class: 'form-control', id: 'message', readonly: true, autofocus: true %>
                      <div class="input-group-addon" id="copy-message" data-toggle="tooltip" data-placement="right" title="Copied!">
                        <span class="glyphicon glyphicon-copy" aria-hidden="true"/>
                      </div>
                  </div>
                  <span class="help-block">Sign above message, scan with mobile, or tap QR to open in wallet. Must use <a href="https://freewallet.io/">FreeWallet</a>.</span>
                </div>
              </p>
              <p>
                <h3>Signature</h3>
                <%= f.text_field :generated_signature, value: '', class: 'form-control' %>
                <span class="help-block">Paste signed result from your wallet.</span>
              </p>
              <p>
                <h3>Address</h3>
                <%= f.text_field :public_key, class: 'form-control' %>
                <span class="help-block">The address you signed the message with.</span>
              </p>

              <p>
                <% if params[:redirect] != nil %>
                  <%= f.hidden_field 'redirect', value: params[:redirect] %>
                <% end %>
                <%= f.submit 'Authenticate', class: 'btn btn-primary' %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
      <script>
        var pusher = new Pusher('e6501f279d2014e1da78', {
          encrypted: true
        });

        var channel = pusher.subscribe('<%= @modal_id %>');
        channel.bind('my_event', function(data) {
          $.ajax({
            url: "<%= ENV['BASE_API_URL'] %>/set_session?account=" + data.user,
            beforeSend: function( xhr ) {
              xhr.overrideMimeType( "text/plain; charset=x-user-defined" );
            }
          })
          .done(function() {
            window.location.replace("<%= ENV['BASE_API_URL'] %>");
          });
        });
      </script>
    </body>
  </html>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6 col-lg-4 col-md-offset-3 col-lg-offset-4">
        <h1 class="text-center" style="margin-bottom: 35px;">Wallet Login</h1>
        <%= form_for @account, url: accounts_path, method: 'POST' do |f| %>
          <% if @account.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@account.errors.count, "error") %> prohibited
                this article from being saved:
              </h2>
              <ul>
                <% @account.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <p>
            <div class="form-group">
              <a href="<%= 'counterparty:' + @tapscan %>">
                <img class="qr pull-left" src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=counterparty:<%= @qr_data %>" />
              </a>
              <h3>Message</h3>
              <div class="input-group">
                <%= f.text_field :generated_message, value: @generated_message,
                  class: 'form-control', id: 'message', readonly: true, autofocus: true %>
                  <div class="input-group-addon" id="copy-message" data-toggle="tooltip" data-placement="right" title="Copied!">
                    <span class="glyphicon glyphicon-copy" aria-hidden="true"/>
                  </div>
              </div>
              <span class="help-block">Sign above message, scan with mobile, or tap QR to open in wallet. Must use <a href="https://freewallet.io/">FreeWallet</a>.</span>
            </div>
          </p>
          <p>
            <h3 style="clear: left;">Signature</h3>
            <%= f.text_field :generated_signature, value: '', class: 'form-control' %>
            <span class="help-block">Paste signed result from your wallet.</span>
          </p>
          <p>
            <h3>Address</h3>
            <%= f.text_field :public_key, class: 'form-control' %>
            <span class="help-block">The address you signed the message with.</span>
          </p>

          <p>
            <% if params[:redirect] != nil %>
              <%= f.hidden_field 'redirect', value: params[:redirect] %>
            <% end %>
            <%= f.submit 'Authenticate', class: 'btn btn-primary' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="modal fade sign-modal" tabindex="-1" role="dialog" aria-labelledby="Sign Message">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
        </div>
      </div>
    </div>
  </div>

  <script>
    var pusher = new Pusher('e6501f279d2014e1da78', {
      encrypted: true
    });

    var channel = pusher.subscribe('<%= @modal_id %>');
    channel.bind('my_event', function(data) {
      $.ajax({
        url: "<%= ENV['BASE_API_URL'] %>/set_session?account=" + data.user,
        beforeSend: function( xhr ) {
          xhr.overrideMimeType( "text/plain; charset=x-user-defined" );
        }
      })
      .done(function() {
        window.location.replace("<%= ENV['BASE_API_URL'] %>");
      });
    });
  </script>
<% end %>

app/views/accounts/show.html.erb
<div class="container" style="margin-top: 25px;">
  <div class="services col-xs-12 col-sm-6 col-md-7 col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Authorized Services</h3>
      </div>
      <div class="panel-body">
        <% if @providers.length > 0 %>
          <% @providers.each do |p| %>
            <div class="col-sm-12 well pull-left" style="width: 100%; padding: 25px;">
              <div class="pull-right" style="margin-bottom: 15px;">
                <%= link_to 'Revoke Access', providers_revoke_path + '?account=' + @account.id.to_s + '&provider=' + p.id.to_s,
                  :class => 'btn btn-danger pull-right' %>
                <a class="btn btn-primary pull-right" style="margin-right: 10px;" role="button" data-toggle="collapse" href="#connection<%= p.id %>" aria-expanded="false" aria-controls="connection">Details</a>
              </div>
              <div class="pull-left">
                <%= image_tag(p.logo, class: "img-thumbnail logo pull-left") %>
                <span class="pull-left">
                  <h3 style="margin-top: 0px; margin-bottom: 0px;"><%= p.name %></h3>
                  <h3 style="margin-top: 0px;"><small><%= p.contact_email %></small></h3>
                </span>
              </div>
              <div class="panel panel-primary collapse" id="connection<%= p.id %>" style="clear: both; position: relative; top: 15px; margin-top: 25px;">
                <div class="panel-heading">
                  <h3 class="panel-title">Connection Info</h3>
                </div>
                <div class="panel-body">
                  <p>
                    <strong>Connected:</strong> <%= @account.connections.find_by(provider_id: p.id).connected_on %></li>
                  </p>
                  <p style="word-wrap: break-word;">
                    <strong>Bearer:</strong> <%= @account.connections.find_by(provider_id: p.id).bearer %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <h5>No services authenticated.</h5>
        <% end %>
      </div>
    </div>
  </div>
  <div class="account col-xs-12 col-sm-6 col-md-5 col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Authparty Account</h3>
      </div>
      <div class="panel-body">
        <p>
          <h5><strong>My Address</strong></h5>
          <% if @account.public_key != nil %>
            <%= @account.public_key %>
          <% else %>
            <%= link_to 'Add address', edit_account_path(@account) %>
          <% end %>
        </p>
        <p>
          <h5><strong>Address Verification</strong></h5>
          <%= @response %>
        </p>
        <p>
          <% if @account.is_broadcasted == false && @account.public_key != nil %>
            <strong>Please Broadcast the following in your wallet:</strong>
            <h5>AUTHPARTY VERIFY-ADDRESS <%= @account.broadcast_code %></h5>
            <strong>Wait for one confirmation then check:</strong>
            <h5><%= link_to 'Confirm Broadcast', '/broadcast?id=' + @account.id.to_s %></h5>
          <% end %>
        </p>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Early Access (XAPEA)</h3>
      </div>
      <div class="panel-body">
        <p>
          <h5><strong>Status: Active</strong></h5>
          <% if @early_access_token != false %>
            You currently have <%= @early_access_count %> XAPEA
          <% else %>
            <% if @address_error == true %>
                This address has never made a transaction <br /><br />
            <% end %>
            A XAPEA token was not found. Get one via <%= link_to 'Swapbot', 'https://swapbot.tokenly.com/bot/mreichardt/authparty#choose'%>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>